import { BaseFragment, createFragmentTemplate } from '@codama/renderers-core';

import {
    addToImportMap,
    createImportMap,
    ImportMap,
    importMapToString,
    mergeImportMaps,
    parseImportInput,
} from './imports';
import { ReactHooksRenderScope } from './options';

export type Fragment = BaseFragment &
    Readonly<{
        imports: ImportMap;
    }>;

function createFragment(content: string): Fragment {
    return Object.freeze({ content, imports: createImportMap() });
}

function isFragment(value: unknown): value is Fragment {
    return typeof value === 'object' && value !== null && 'content' in value;
}

export function fragment(template: TemplateStringsArray, ...items: unknown[]): Fragment {
    return createFragmentTemplate(template, items, isFragment, mergeFragments);
}

export function mergeFragments(
    fragments: (Fragment | undefined)[],
    mergeContent: (contents: string[]) => string,
): Fragment {
    const filteredFragments = fragments.filter((f): f is Fragment => f !== undefined);
    return Object.freeze({
        content: mergeContent(filteredFragments.map(f => f.content)),
        imports: mergeImportMaps(filteredFragments.map(f => f.imports)),
    });
}

export function use(importInput: string, module: string): Fragment {
    const importInfo = parseImportInput(importInput);
    return addFragmentImports(createFragment(importInfo.usedIdentifier), module, [importInput]);
}

export function mergeFragmentImports(frag: Fragment, importMaps: ImportMap[]): Fragment {
    return Object.freeze({ ...frag, imports: mergeImportMaps([frag.imports, ...importMaps]) });
}

export function addFragmentImports(frag: Fragment, module: string, importInputs: string[]): Fragment {
    return Object.freeze({ ...frag, imports: addToImportMap(frag.imports, module, importInputs) });
}

export function getExportAllFragment(module: string): Fragment {
    return fragment`export * from '${module}';`;
}

export function getPageFragment(
    page: Fragment,
    scope: Pick<ReactHooksRenderScope, 'clientPackage' | 'kitImportStrategy'>,
): Fragment {
    const header = fragment`/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */`;
    const useClientDirective = fragment`'use client';`;
    const imports =
        page.imports.size === 0
            ? undefined
            : fragment`${importMapToString(page.imports, scope.clientPackage, scope.kitImportStrategy)}`;
    return mergeFragments([header, useClientDirective, imports, page], cs => cs.join('\n\n'));
}
